name: CI/CD Pipeline
on: [push, pull_request]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (if any)
        run: echo "No dependencies needed for static site"

      - name: Run tests (simulated)
        run: |
          echo "Verifying HTML structure..."
          grep -q "<html" index.html && echo "HTML valid" || exit 1

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
